C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\module.py:911: UserWarning: expandable_segments not supported on this platform (Triggered internally at ..\c10/cuda/CUDAAllocatorConfig.h:30.)
  return self._apply(lambda t: t.cuda(device))
C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\module.py:911: UserWarning: expandable_segments not supported on this platform (Triggered internally at ..\c10/cuda/CUDAAllocatorConfig.h:30.)
  return self._apply(lambda t: t.cuda(device))
AttGAN model loaded successfully!
AttGAN model loaded successfully!
Namespace(c_dim=5, c2_dim=8, celeba_crop_size=178, image_size=256, g_conv_dim=64, d_conv_dim=64, g_repeat_num=6, d_repeat_num=6, lambda_cls=1, lambda_rec=10, lambda_gp=10, selected_attrs=['Black_Hair', 'Blond_Hair', 'Brown_Hair', 'Male', 'Young'], dataset='MAADFace', g_lr=0.0001, d_lr=0.0001, beta1=0.5, beta2=0.999, training_image_num=5, inference_image_num=5, start_index=0, reward_weight=0.5, test_iters=200000, num_workers=1, mode='inference', images_dir='MAAD-Face/data/train', attr_path='MAAD-Face/MAAD_Face_filtered.csv', log_dir='stargan/logs', model_save_dir='stargan_celeba_256/models', sample_dir='stargan/samples', result_dir='result_inference', epsilon_start=0.95, epsilon_end=0.04, epsilon_decay=1000, batch_size=1, agent_lr=0.0001, gamma=0.96, target_update_interval=5, memory_capacity=512, max_steps_per_episode=20, action_dim=4, noise_level=0.005, feature_extractor_name='mesonet', alpha=0.8, beta_start=0.35, beta_frames=4000, prior_eps=1e-06, v_min=-5, v_max=5, atom_size=11, n_step=5, pgd_iter=1, dct_iter=1, dct_coefficent=3, dct_clamp=2)
Finished preprocessing the MAADFace dataset...
Successfully loaded weights into meso4 model.
Successfully loaded weights into mesoinception4 model.
[INFO] Rainbow DQN model loaded successfully: stargan_celeba_256/models\final_rainbow_dqn.pth
Loading the trained models from step 200000...
Traceback (most recent call last):
  File "C:\Users\Bandi\Desktop\Fork\IT-RAP\attgan_main.py", line 137, in <module>
    main(config)
  File "C:\Users\Bandi\Desktop\Fork\IT-RAP\attgan_main.py", line 52, in main
    solver.inference_rainbow_dqn(dataset_loader, result_dir=config.result_dir, start_idx=300)
  File "C:\Users\Bandi\Desktop\Fork\IT-RAP\attgan_solver.py", line 393, in inference_rainbow_dqn
    original_gen_image, _ = self.G(x_real, c_trg)
                            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\Desktop\Fork\IT-RAP\stargan_model.py", line 69, in forward
    x = layer(x)
        ^^^^^^^^
  File "C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bandi\anaconda3\envs\antiforgery\Lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [64, 8, 7, 7], expected input[1, 16, 256, 256] to have 8 channels, but got 16 channels instead
